# Generated by Django 6.0.8 on 2026-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_options_alter_solution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='function_files',
            field=models.TextField(blank=True, default='[]', help_text='函数题专用：JSON 数组 [{"name": "...", "content": "..."}]'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('standard', '标准题'), ('function', '函数题')], default='standard', max_length=10),
        ),
    ]
