# Generated by Django 6.0.8 on 2026-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problem_function_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='interactive_config',
            field=models.TextField(blank=True, default='{}', help_text='交互题专用：JSON 对象 {"num_processes": 1, "user_io": "fifo_io"}'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='function_files',
            field=models.TextField(blank=True, default='[]', help_text='函数题/交互题专用：JSON 数组 [{"name": "...", "content": "..."}]'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('standard', '标准题'), ('function', '函数题'), ('interactive', '交互题')], default='standard', max_length=16),
        ),
    ]
