# Generated by Django 6.0.8 on 2026-10-06 14:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_two_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_object_key),
        ),
    ]
