#!/usr/bin/env python3
"""Generate ``ojsec_policy.h`` from ``seccomp-execute.json``.

ojsec (see ojsec.c) installs the execute-phase seccomp filter inside judge
containers. The BPF program needs numeric x86_64 syscall numbers, so this
script resolves the names in seccomp-execute.json through the build host's
<sys/syscall.h> and emits a sorted, deduplicated C array.

Usage (from the repo root, on an x86_64 Linux build host with gcc)::

    python3 docker/judge/gen_ojsec_policy.py

then rebuild the static binary::

    gcc -O2 -static -s -o docker/judge/ojbin/ojsec docker/judge/ojsec.c
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROFILE = HERE / "seccomp-execute.json"
HEADER = HERE / "ojsec_policy.h"


def resolve_syscall_numbers() -> dict[str, int]:
    """Map syscall name -> x86_64 number via gcc's <sys/syscall.h>."""
    src = b"#include <sys/syscall.h>\n"
    cpp = subprocess.run(
        ["gcc", "-E", "-dM", "-x", "c", "-"],
        input=src, capture_output=True, check=True,
    )
    table: dict[str, int] = {}
    for line in cpp.stdout.decode().splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] == "#define" and parts[1].startswith("__NR_"):
            name = parts[1][len("__NR_"):]
            try:
                table[name] = int(parts[2], 0)
            except ValueError:
                pass
    return table


def main() -> int:
    profile = json.loads(PROFILE.read_text())
    names = sorted(set(profile["syscalls"][0]["names"]))
    table = resolve_syscall_numbers()

    missing = [n for n in names if n not in table]
    if missing:
        print("unresolved syscall names on this architecture:", missing,
              file=sys.stderr)
        return 1
    numbers = sorted(table[n] for n in names)
    if len(set(numbers)) != len(numbers):
        print("name->number mapping is not injective", file=sys.stderr)
        return 1

    audit = "\n".join(
        f" *   {n:<22} {table[n]}" for n in names
    )
    body = f"""/*
 * AUTO-GENERATED by gen_ojsec_policy.py from seccomp-execute.json.
 * DO NOT EDIT BY HAND — change seccomp-execute.json, re-run the generator
 * and rebuild docker/judge/ojbin/ojsec.
 *
 * x86_64 execute-phase whitelist ({len(numbers)} syscalls):
{audit}
 */
#ifndef OJSEC_POLICY_H
#define OJSEC_POLICY_H

#define OJSEC_POLICY_COUNT {len(numbers)}

static const int ojsec_policy_nrs[OJSEC_POLICY_COUNT] = {{
{chr(10).join("    %d," % n for n in numbers)}
}};

#endif /* OJSEC_POLICY_H */
"""
    HEADER.write_text(body)
    print(f"wrote {HEADER} with {len(numbers)} syscalls")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
