/*
 * AUTO-GENERATED by gen_ojsec_policy.py from seccomp-execute.json.
 * DO NOT EDIT BY HAND — change seccomp-execute.json, re-run the generator
 * and rebuild docker/judge/ojbin/ojsec.
 *
 * x86_64 execute-phase whitelist (149 syscalls):
 *   access                 21
 *   arch_prctl             158
 *   brk                    12
 *   capget                 125
 *   chdir                  80
 *   chmod                  90
 *   clock_getres           229
 *   clock_gettime          228
 *   clock_nanosleep        230
 *   clone                  56
 *   clone3                 435
 *   close                  3
 *   close_range            436
 *   connect                42
 *   dup                    32
 *   dup2                   33
 *   dup3                   292
 *   epoll_create1          291
 *   epoll_ctl              233
 *   epoll_pwait            281
 *   epoll_wait             232
 *   eventfd2               290
 *   execve                 59
 *   exit                   60
 *   exit_group             231
 *   faccessat2             439
 *   fadvise64              221
 *   fallocate              285
 *   fchdir                 81
 *   fchmod                 91
 *   fchmodat               268
 *   fcntl                  72
 *   fdatasync              75
 *   flock                  73
 *   fstat                  5
 *   fstatfs                138
 *   fsync                  74
 *   ftruncate              77
 *   futex                  202
 *   getcwd                 79
 *   getdents64             217
 *   getegid                108
 *   geteuid                107
 *   getgid                 104
 *   getpeername            52
 *   getpgrp                111
 *   getpid                 39
 *   getppid                110
 *   getpriority            140
 *   getrandom              318
 *   getresgid              120
 *   getresuid              118
 *   getrlimit              97
 *   getrusage              98
 *   getsockname            51
 *   getsockopt             55
 *   gettid                 186
 *   getuid                 102
 *   ioctl                  16
 *   kill                   62
 *   lseek                  8
 *   lstat                  6
 *   madvise                28
 *   mkdir                  83
 *   mkdirat                258
 *   mknodat                259
 *   mmap                   9
 *   mprotect               10
 *   mremap                 25
 *   msync                  26
 *   munmap                 11
 *   nanosleep              35
 *   newfstatat             262
 *   openat                 257
 *   pipe2                  293
 *   pkey_alloc             330
 *   pkey_free              331
 *   pkey_mprotect          329
 *   poll                   7
 *   ppoll                  271
 *   prctl                  157
 *   pread64                17
 *   preadv                 295
 *   prlimit64              302
 *   pselect6               270
 *   pwrite64               18
 *   pwritev                296
 *   read                   0
 *   readlink               89
 *   readlinkat             267
 *   readv                  19
 *   recvfrom               45
 *   rename                 82
 *   renameat               264
 *   restart_syscall        219
 *   rmdir                  84
 *   rseq                   334
 *   rt_sigaction           13
 *   rt_sigprocmask         14
 *   rt_sigqueueinfo        129
 *   rt_sigreturn           15
 *   rt_sigsuspend          130
 *   rt_sigtimedwait        128
 *   sched_getaffinity      204
 *   sched_yield            24
 *   select                 23
 *   semctl                 66
 *   semget                 64
 *   semop                  65
 *   semtimedop             220
 *   sendfile               40
 *   sendto                 44
 *   set_robust_list        273
 *   set_tid_address        218
 *   setitimer              38
 *   setpgid                109
 *   setsockopt             54
 *   shmat                  30
 *   shmctl                 31
 *   shmdt                  67
 *   shmget                 29
 *   shutdown               48
 *   sigaltstack            131
 *   socket                 41
 *   socketpair             53
 *   statfs                 137
 *   statx                  332
 *   symlink                88
 *   symlinkat              266
 *   sysinfo                99
 *   tgkill                 234
 *   timer_create           222
 *   timer_delete           226
 *   timer_getoverrun       225
 *   timer_gettime          224
 *   timer_settime          223
 *   timerfd_create         283
 *   timerfd_gettime        287
 *   timerfd_settime        286
 *   umask                  95
 *   uname                  63
 *   unlink                 87
 *   unlinkat               263
 *   utimensat              280
 *   vfork                  58
 *   wait4                  61
 *   waitid                 247
 *   write                  1
 *   writev                 20
 */
#ifndef OJSEC_POLICY_H
#define OJSEC_POLICY_H

#define OJSEC_POLICY_COUNT 149

static const int ojsec_policy_nrs[OJSEC_POLICY_COUNT] = {
    0,
    1,
    3,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    23,
    24,
    25,
    26,
    28,
    29,
    30,
    31,
    32,
    33,
    35,
    38,
    39,
    40,
    41,
    42,
    44,
    45,
    48,
    51,
    52,
    53,
    54,
    55,
    56,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    72,
    73,
    74,
    75,
    77,
    79,
    80,
    81,
    82,
    83,
    84,
    87,
    88,
    89,
    90,
    91,
    95,
    97,
    98,
    99,
    102,
    104,
    107,
    108,
    109,
    110,
    111,
    118,
    120,
    125,
    128,
    129,
    130,
    131,
    137,
    138,
    140,
    157,
    158,
    186,
    202,
    204,
    217,
    218,
    219,
    220,
    221,
    222,
    223,
    224,
    225,
    226,
    228,
    229,
    230,
    231,
    232,
    233,
    234,
    247,
    257,
    258,
    259,
    262,
    263,
    264,
    266,
    267,
    268,
    270,
    271,
    273,
    280,
    281,
    283,
    285,
    286,
    287,
    290,
    291,
    292,
    293,
    295,
    296,
    302,
    318,
    329,
    330,
    331,
    332,
    334,
    435,
    436,
    439,
};

#endif /* OJSEC_POLICY_H */
