# Generated by Django 6.0.8 on 2026-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_submission_claim_token_submission_claimed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compile_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='judge_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='result_written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='tests_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
