# Generated by Django 6.0.8 on 2026-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_submission_compile_done_at_submission_enqueued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='container_acquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
