# Generated by Django 6.0.8 on 2026-09-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_submission_container_acquired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontestresult',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Partial', 'Partial'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compile Error', 'Compile Error'), ('System Error', 'System Error')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='submissiontestresult',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Partial', 'Partial'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Skipped', 'Skipped')], max_length=30),
        ),
    ]
