# Generated by Django 6.0.8 on 2026-10-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_submissiontestresult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgemachine',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='judgemachine',
            name='weight',
        ),
    ]
