# Generated by Django 6.0.8 on 2026-09-26 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('category', models.CharField(choices=[('bug', '问题反馈'), ('feature', '功能建议'), ('account', '账号问题'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('body', models.TextField(max_length=5000, verbose_name='内容')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='留空时自动使用账号邮箱', max_length=254, verbose_name='联系邮箱')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('email_sent', models.BooleanField(default=False, verbose_name='通知邮件已发送')),
                ('email_error', models.TextField(blank=True, default='', verbose_name='通知邮件错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tickets_tic_status_15eec8_idx')],
            },
        ),
    ]
